web:
  image: wordpress:4.8-php7.0-apache
  volumes:
    - ./wp/wp-content:/var/www/html/wp-content
  ports:
    - "8080:80"
  links:
    - db
  environment:
    WORDPRESS_DB_PASSWORD: null
    WORDPRESS_DB_NAME: php_dev
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_HOST: db:3306



db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=php_dev
